### ISSUE TITLE
Error with the dockerfile

### ISSUE THREAD

**Issue by balabalaman** [ratibor78/geostat#19]
Hi,

thank you for provided a great script, and it just look lovely to have. But I do not know why the container cannot be started with your dockerfile. Logs are below, any hints?

Error log is here:
------------------------------------------------
Traceback (most recent call last):
  File "//./geoparser.py", line 17, in <module>
    from IPy import IP as ipadd
  File "/usr/lib/python3.10/site-packages/IPy.py", line 1025, in <module>
    class IPSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

**Comment by ratibor78** [comment]
Hi @balabalaman, year I also have found that issue, the time was passed and something was changing in Alpine image I giess, I'll reproduce this error and fix it soon.

**Comment by balabalaman** [comment]
Thanks bro.

**Comment by ratibor78** [comment]
Hi again @balabalaman I have fixed the issue, the problem was in the latest version of Alpine Docker image, it has a Python3.10, and it looks that some libs have issues with my code, so I downgraded the image to alpine:3.9 and tested it. Now it's worked OK.  So you need to update and rebuild the Docker image, also maybe better clear the docker build cache and check that your newly built docker image for geostat are based on alpine 3.9. 

Good night bro ! :)
