### ISSUE TITLE
Multiple log files

### ISSUE THREAD

**Issue by KotNeo** [ratibor78/geostat#2]
What if there are several access.log (Nginx) files?
/var/log/nginx/access1.log
and
/var/log/nginx/access2.log

**Comment by ratibor78** [comment]
Sorry for late reply, I have missed this issue opening.
Well, adding multiple logs parsing availability may have sense, I'll take a look, what I can do with it.

**Comment by ratibor78** [comment]
Hi @KotNeo, did you mean this multiple logs will be from the same Nginx or Apache server or from different?

Because the   GEO data will combine in the InfluxDB so you can't be able to understand which GEO data from which log was.  I guess it can be done by running two different versions of scripts with different configs for the different logs so you can put GEO data in separated tables in InfluxDB. 

I'll create a docker file also image too, so it can give a speed running of this script.
